management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    beans:
      enabled: true
  info:
    git:
      mode: full
      
#spring.profiles: local      
#spring: 
#  cloud:
#    config:
#      enabled: false
#    loadbalancer:
#      ribbon:
#        enabled: false     
      
myvalue: Local Value
kkSecretPropertyName: Local KK Secret