spring:
  application:
    name: azure-keyvault-demo
  profiles: local 
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false     
myvalue: Local Value
kkSecretPropertyName: Local KK Secret  
      
---
spring:
  application:
    name: azure-keyvault-demo
  profiles: cloud
    #active: dev 
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false     
myvalue: Cloud Value
kkSecretPropertyName: Cloud KK Secret  
  
---
spring:
  application:
    name: azure-keyvault-demo
  profiles: dev
    #active: dev 
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false     
myvalue: Dev Cloud Value
      
#running on PCF - read from VCAP service
azure:
  keyvault:
    uri: ${vcap.services.azure-vault-service.credentials.vaultUri}
    client-id: ${vcap.services.azure-vault-service.credentials.clientId}
    client-key: ${vcap.services.azure-vault-service.credentials.clientSecret}
    tenant-id: ${vcap.services.azure-vault-service.credentials.tenant-id}
    
---
spring:
  application:
    name: azure-keyvault-demo
  profiles: test 
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false     
  